version: "3"

services:
  ipfs:
    image: ceramicnetwork/go-ipfs-daemon:latest
    volumes:
      - ./volumes/ipfs:/data/ipfs
    ports:
      - 5001:5001
      - 8011:8011
    environment:
      IPFS_ENABLE_S3: true
      IPFS_S3_REGION: us-east-1
      IPFS_S3_BUCKET_NAME: usher-ceramic
      IPFS_S3_ROOT_DIRECTORY: ipfs
      IPFS_S3_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      IPFS_S3_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
      IPFS_S3_KEY_TRANSFORM: next-to-last/2

  ceramic:
    image: ceramicnetwork/js-ceramic:latest
    volumes:
      - ./volumes/ceramic:/root/.ceramic
    environment:
      NODE_ENV: production
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
    ports:
      - 7007:7007
    depends_on:
      - ipfs
